# -*- coding: utf-8 -*-
"""mlautomaticlanguagetranslator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1URDswKXNIx_yl9N_xo6KvUo9RZ7P_BPM
"""

!pip install git+https://github.com/srivatsan88/keras.ocr.git

pip install git+https://github.com/faustomorales/keras-ocr.git#egg=keras-ocr

import matplotlib.pyplot as plt
import keras_ocr

pip install googletrans==3.1.0a0



pipline = keras_ocr.pipeline.Pipeline()

#@{run:"auto"}
yes= 'https://boomsumo.com/wp-content/uploads/2017/05/Inspirational-life-quotes-Life-Sayings-Sometime-Deserve-Quotes-about-life.jpg' #@param 
images=[keras_ocr.tools.read(images) for images in [ 
    yes,
   'https://image.shutterstock.com/image-vector/creative-colorful-sentence-text-design-260nw-1827881240.jpg']]
prediction = pipline.recognize(images)
import keras_ocr 

pipeline = keras_ocr.pipeline.Pipeline()

images = [
  keras_ocr.tools.read(url) for url in [
                                        
      yes,        
      #'https://storage.googleapis.com/gcptutorials.com/examples/keras-ocr-img-2.png'
  ]
]

#print(images[0])
#print(images[1])

prediction_groups = pipeline.recognize(images)

predicted_image_1 = prediction_groups[0]


#predicted_image_2 = prediction_groups[1]
#for text, box in predicted_image_2:
#  print(text)

guh =''
for text,box in predicted_image_1:
     guh += text + " " 
print(guh)


#@{run:"auto"}
#@title taking input  
from googletrans import Translator
translator = Translator()
key = "mr:marathi" #@param["hi: hindi","En:english","mr:marathi"]
key=key[0:2]
print(key)
out = translator.translate(guh, dest=key)
print(out.text)